### ISSUE TITLE
can not find ui_stopwatchviewer.h

### ISSUE THREAD

**Issue by zhuzunjie17** [mp3guy/Stopwatch#4]
https://github.com/mp3guy/Stopwatch/blob/683c53f27ade849d857835979ec6b4d72da0a32a/src/stopwatchviewer.h#L15
**stopwatchviewer.h**  include a .h file "../build/ui_stopwatchviewer.h" however i can not found it
have i missed something?

**Comment by kemangjaka** [comment]
Maybe you found the solution, but for who met the same problem...
ui_stopwatchviewer.h is generated after you build the code. 
If you change 
#include "../build/ui_stopwatchviewer.h"
to
#include "./build/ui_stopwatchviewer.h"
, you will successfully run the code.

**Comment by zhuzunjie17** [comment]
I have found the solution later that time, but sincerely thanks for your answer, I will close this issue.
